### ISSUE TITLE
Error importing User from django auth models

### ISSUE THREAD

**Issue by eronmedeiros** [PyCQA/pylint-django#278]
Hey there,
I'm getting an error and I don't know why it is showing up.
It is a new django project. I'm running everything normally.

Except, on every code that imports:
`from django.contrib.auth.models import User`

It says:
`User model imported from django.contrib.auth.models pylint(imported-auth-user)`

It shows no error code, so I can't even remove it like I did with function doc string errors, in the .pylintrc file.

**Comment by carlio** [comment]
@eronmedeiros I think that's because that error message was missing the decorator. Can you try installing pylint-django from this branch and see if it fixes things? https://github.com/PyCQA/pylint-django/tree/bugfix/278-add-auth-user-error-code

@atodorov I think my branch here will fix things: https://github.com/PyCQA/pylint-django/tree/bugfix/278-add-auth-user-error-code

**Comment by atodorov** [comment]
> @atodorov I think my branch here will fix things: https://github.com/PyCQA/pylint-django/tree/bugfix/278-add-auth-user-error-code

@carlio I've merged this into master. Closing this issue.

**Comment by gdowdy3** [comment]
Hey guys, I encountered the same error and disabled it using the error number provided by the bug fix described above.  So thanks for providing that error number.  👍 

I'm wondering, though: why is that error message appearing in the first place? The line of code 
```python
from django.contrib.auth.models import User
```
comes straight from the Django documentation: https://docs.djangoproject.com/en/3.1/topics/auth/default/

Why should it give an error?

**Comment by atodorov** [comment]
> comes straight from the Django documentation: https://docs.djangoproject.com/en/3.1/topics/auth/default/
> 
> Why should it give an error?

https://github.com/PyCQA/pylint-django/issues/244

FTR Django doesn't always document or even follow its practices.

**Comment by IRezig** [comment]
Hello guys,
I had this issue too and I fixed it by 

1. Installing Pylint
`pip install pylint-django`

2. create .pylintrc file (in racin of your project) and add:
`--load-plugins pylint_django`
Hope that help you 

Bonne journée

**Comment by cyclops26** [comment]
> Hey guys, I encountered the same error and disabled it using the error number provided by the bug fix described above. So thanks for providing that error number. 👍
> 
> I'm wondering, though: why is that error message appearing in the first place? The line of code
> 
> ```python
> from django.contrib.auth.models import User
> ```
> 
> comes straight from the Django documentation: https://docs.djangoproject.com/en/3.1/topics/auth/default/
> 
> Why should it give an error?

@gdowdy3 I believe it might be because they recognize that people may replace the User model with their own custom model.

Tucked away in the docs is this [https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#referencing-the-user-model](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#referencing-the-user-model)

Not saying that the other documentation doesn't need updating, but this would be my suspicion.
